[package]
name = "result_and_option"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[[bin]]
name = "hw1"
path = "src/hw1.rs"


[[bin]]
name = "hw2"
path = "src/hw2.rs"